name: floppy_birds
description: "floppy birds game in flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1

  #app specific settings
  rename_app: ^1.6.1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3
  change_app_package_name: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  flutter_gen_runner:
  injectable_generator:

  flutter_oss_licenses: ^3.0.2
  custom_lint: ^0.7.5
  custom_lints:
    path: custom_lints

flutter_gen:
  output: lib/core/resources/gen
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/

# didn't use fonts for this app

flutter_native_splash:

  color: "#ffffff"
  image: assets/image/png/green_app_logo.png
  android_12:
    color: "#ffffff"
    image: assets/image/png/green_app_logo.png
    icon_background_color: "#ffffff"
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_foreground: "assets/image/png/green_app_logo.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 24
  image_path: "assets/image/png/green_app_logo.png"
  adaptive_icon_padding: true